cabal-version:      3.0
name:               graded-monads
version:            0.1.0.0
description:
bug-reports:        https://github.com/solomon-b/aggregate-errors
author:             solomon
maintainer:         ssbothwell@gmail.com
extra-source-files: CHANGELOG.md
tested-with:
    GHC == 9.0.2,
    GHC == 9.2.8,
    GHC == 9.4.8,
    GHC == 9.6.7,
    GHC == 9.8.4,
    GHC == 9.10.3,
    GHC == 9.12.4

common common-settings
  default-language:    Haskell2010
  ghc-options:
    -Wall
    -Wcpp-undef
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Werror=missing-home-modules

common common-libraries
  build-depends:
    , base >= 4.15 && < 5
    , monoidal-functors
    , sorted-type-sets
    , these >= 1.1.1 && < 1.3
    , mtl >= 2.2.2 && < 2.4

executable aggregated-errors
  -- A clever trick for aggregating different error types in a single do block.
  import:
    , common-libraries
    , common-settings
  main-is:
    Main.hs
  hs-source-dirs:
    examples/aggregated-errors
  build-depends:
    , graded-monads

executable aggregated-logs
  -- A clever trick for aggregating different error types in a single do block.
  import:
    , common-libraries
    , common-settings
  main-is:
    Main.hs
  hs-source-dirs:
    examples/aggregated-logs
  build-depends:
    , graded-monads

library
  import:
    , common-libraries
    , common-settings
  hs-source-dirs:
    src
  exposed-modules:
    Control.Monad.Graded
    Control.Monad.Graded.Except
    Control.Monad.Graded.Except.Class
    Control.Monad.Graded.Writer
    Control.Monad.Graded.Writer.Class

library laws
  import:
    , common-settings
  visibility:
    public
  hs-source-dirs:
    laws
  exposed-modules:
    Control.Monad.Graded.Laws
  build-depends:
    , base
    , graded-monads
    , monoidal-functors
    , sorted-type-sets
    , hedgehog
    , hedgehog-classes

test-suite graded-monads-test
  import:
    , common-settings
  type:
    exitcode-stdio-1.0
  main-is:
    Main.hs
  hs-source-dirs:
    test
  build-depends:
    , base
    , graded-monads
    , graded-monads:laws
    , monoidal-functors
    , sorted-type-sets
    , hedgehog
    , hedgehog-classes
